version: '3.1'

services:
  market_pg:
    image: postgres:15.1
    container_name: blog_pg
    environment:
      DB_DATABASE: blog
      DB_USERNAME: ublog
      DB_PASSWORD: secret123456
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql